#%RAML 0.8
---
title: VTEX API Protocol
version: v0.3.0+beta
protocols: [ HTTPS ]
baseUri: https://api.vtexcommerce.com.br/{accountName}/protocol-example
baseUriParameters:
    accountName:
        description: Identifica a conta do cliente VTEX.
traits:
  - paged: !include traits/paged.yaml
resourceTypes: !include resourceTypes/baseResourceTypes.yaml
/myResources:
  get:
    is: [ paged ]
    responses:
      206:
        body:
          application/vnd.vtex.myResource.v1+json:
            example: |
              [
                {
                  "someProperty": "property value",
                  "otherProperty": 213
                },
                {
                  "someProperty": "another property value",
                  "otherProperty": 123
                }
              ]
  /{resourceId}:
    type: versioned
    get:
    put:
    patch:
    delete:
